<ul class="breadcrumb">
    <li>
        <a href="<?php echo $this->baseUrl(); ?>">Home</a> <span class="divider">/</span>
    </li>
    <li class="active">Usuario </li>
</ul>
<script>
    <!--
    $(document).ready(function(){
        $("#dataCadastro").mask("99/99/9999");
        $('#myModal').hide();
    });
    $(function() {
        $( "#dataCadastro" ).datepicker();
    });
    -->
</script>
<div class="btn-group">
    <form id="formulario" class="appnitro"  method="post">
        <div class="form_description">
            <h2></span><span class="label label-info">Usuarios</span></h2>
        </div>
        <table class="table table-striped table-bordered table-condensed" width="100%">
            <tr>
                <td>
                    <div class="field">
                        <label class="description" for="nome">Nome </label>
                        <div>
                            <input id="nome" name="nome" class="element text large" type="text" maxlength="45" value=""/> 
                        </div>                 
                    </div>
                </td>
                <td>
                    <div class="field">
                        <label class="description" for="email">Email </label>
                        <div>
                            <input id="email" name="email" class="element text large" type="text" maxlength="45" value=""/> 
                        </div> 
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="field">
                        <label class="description" for="equipe">Equipe </label>
                        <div>
                            <select class="element select medium" id="equipe" name="equipe"> 
                                <option value="" >...</option>
                                <?php
                                $equipe = new Model_DbTable_Equipe();
                                foreach ($equipe->fetchAll() as $row) {
                                    ?><option value="<?php echo $row->id; ?>"><?php echo $row->nome; ?></option><?php
                            }
                                ?>

                            </select>
                        </div> 
                    </div>
                </td>
                <td>
                    <div class="field">
                        <label class="description" for="dataCadastro">Data do Cadastro</label>
                        <div>
                            <input id="dataCadastro" name="dataCadastro" class="element text small" type="text" maxlength="45" value=""/> 
                        </div>
                    </div>
                </td>
                <td></td>
            </tr>
            <tr>
                <td colspan="3" >
                    <div class="buttons">
                        <input class="btn" id="buscar" class="button_text" type="submit" name="submit" value="Buscar" />
                        <input class="btn" id="buscar" class="button_text" type="reset" name="submit" value="Limpar" />

                        <a class="btn" href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'create')); ?>" title="Incluir novo">Incluir novo</a>
                    </div>
                </td>
            </tr>
        </table>
    </form>

</div>

<div>

    <table class="table table-striped table-bordered table-condensed" cellspacing="1" cellpadding="1" border="1" width="500">
        <?php if (count($this->usuarios) > 0) { ?>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Equipe</th>
                    <th>Data de Cadastro</th>
                    <th>A&ccedil;&otilde;es</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->usuarios as $row) { ?>
                    <tr>
                        <?php $dataCadastro = new Zend_Date($row->data_cadastro); ?>
                        <td><?php echo $row->id; ?></td>
                        <td><?php echo $this->escape($row->nome); ?></td>
                        <td><?php echo $this->escape($row->email); ?></td>
                        <?php $equipe = $row->findParentRow('Model_DbTable_Equipe', 'Equipe'); ?>
                        <td><?php echo $this->escape($equipe->nome); ?></td>
                        <td><?php echo $this->escape($dataCadastro->get('dd/MM/yyyy')); ?></td>
                        <td>
                            <div class="btn-group" >

                                <a class="btn" 
                                   href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'edit', 'id' => $row->id)); ?>" 
                                   title="Editar">Editar</a>
                                &nbsp;
                                <?php
                                $atividade = new Model_DbTable_Atividade();
                                $atividades = $atividade->fetchAll("usuario_id = " . $row->id,null,null,null);
                                if ($atividades != null && count($atividades) == 0) {
                                    ?>
                                    <a class="btn" data-toggle="modal" href="<?php echo $row->id; ?>#myModal" title="Apagar">Apagar</a>
                                <? } ?>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>

        <?php } else { ?>
            <thead>
                <tr>
                    <th><p>Nenhum registro encontrado.</p></th>
            </tr>
            </thead>
        <?php } ?>
    </table>
</div>
<div id="paginacao">
    <?php if (!is_null($this->usuarios)) { ?>
        <?php echo $this->paginationControl($this->usuarios, 'Sliding', 'paginacao.phtml'); ?>
    <?php } ?>
</div>
<div class="modal" id="myModal" class="modal hide fade in" style="display: block;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Excluir Registro</h3>
    </div>
    <div class="modal-body">
        <p>Deseja excluir o registro?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" >Cancelar</a>
        <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'delete', 'id' => $row->id)); ?>"
           class="btn btn-primary">Confirmar</a>
    </div>
</div>