<div>
    <ul class="breadcrumb">
        <li>
            <a href="<?php echo $this->baseUrl(); ?>">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller' => 'modulo', 'action' => 'index')); ?>">Modulo</a> <span class="divider">/</span>
        </li>
        <li class="active">Novo</li>
    </ul>
</div>
<script>
    <!--
        $(document).ready(function(){
            $("#telefone").mask("9999-9999");
            $("#cpf").mask("999.999.999-99");
            $("#cep").mask("99999-999");
            $("#dataEntrega").mask("99/99/9999");
            $("#formulario").validate({
                rules: {
                    nome: 'required',
                    dataEntrega: 'required',
                    descricao: 'required'
                },
                messages: {
                    nome: '<span class="label label-important">* Campo Obrigatório</span>',
                    dataEntrega: ' <span class="label label-important">* Campo Obrigatório</span>',
                    descricao: ' <span class="label label-important">* Campo Obrigatório</span>'
                }
            });
        });
        $(function() {
            $( "#dataEntrega" ).datepicker();
        });
        -->
</script>

<div id="form_container">
   <img id="top"  src="<?php echo $this->baseUrl(); ?>/img/top.png" alt="">
    <form id="formulario" class="appnitro"  method="post">
        <div class="form_description">
            <h2><span class="label label-info">Cadastrar Modulo</span></h2>
        </div>						
        <ul >

            <li id="li_1" >
                <label class="description" for="nome">Nome </label>
                <div>
                    <input id="nome" name="nome" class="element text medium" type="text" maxlength="45" value=""/> 
                </div>

            </li>
            <li id="li_3" >
                <label class="description" for="dataEntrega">Data da Entrega </label>
                <div>
                    <input id="dataEntrega" name="dataEntrega" class="element text small" type="text" maxlength="45" value=""/> 
                </div>
            </li>
            <li id="li_2" >
                <label class="description" for="descricao">Descrição </label>
                <div>
                    <textarea id="descricao" name="descricao" class="element textarea small"></textarea> 
                </div> 
            </li>
            <li class="buttons">
                <input type="hidden" name="form_id" value="394016" />

                <input class="btn" id="saveForm" class="button_text" type="submit" name="submit" value="Salvar" />
                <input class="btn" id="limpar" class="button_text" type="reset" name="submit" value="Limpar" />
                <a class="btn" href="<?php echo $this->url(array('controller' => 'modulo', 'action' => 'index')); ?>"><b>Cancelar</b></a>
            </li>
        </ul>
        <img id="bottom" src="<?php echo $this->baseUrl(); ?>/img/bottom.png" alt="">
    </form>	

</div>

