<ul class="breadcrumb">
    <li>
        <a href="<?php echo $this->baseUrl(); ?>">Home</a> <span class="divider">/</span>
    </li>
    <li class="active">Modulo </li>
</ul>
<script>
    <!--
    $(document).ready(function(){
        $("#dataEntrega").mask("99/99/9999");
        $('#myModal').hide();
    });
    $(function() {
        $( "#dataEntrega" ).datepicker();
    });
    -->
</script>
<div class="btn-group">
    <form id="formulario" class="appnitro"  method="post">
        <div class="form_description">
            <h2></span><span class="label label-info">Modulos</span></h2>
        </div>
        <table class="table table-striped table-bordered table-condensed" width="100%">
            <tr>
                <td>
                    <div class="field">
                        <label class="description" for="nome">Nome </label>
                        <div>
                            <input id="nome" name="nome" class="element text large" type="text" maxlength="45" value=""/> 
                        </div>                 
                    </div>
                </td>
                <td>
                    <div class="field">
                        <label class="description" for="dataEntrega">Data da Entrega </label>
                        <div>
                            <input id="dataEntrega" name="dataEntrega" class="element text small" type="text" maxlength="45" value=""/> 
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="buttons">
                        <input class="btn" id="buscar" class="button_text" type="submit" name="submit" value="Buscar" />
                        <input class="btn" id="buscar" class="button_text" type="reset" name="submit" value="Limpar" />

                        <a class="btn" href="<?php echo $this->url(array('controller' => 'modulo', 'action' => 'create')); ?>" title="Incluir novo">Incluir novo</a>
                    </div>
                </td>
            </tr>
        </table>
    </form>

</div>

<div>
    
    <table class="table table-striped table-bordered table-condensed" cellspacing="1" cellpadding="1" border="1" width="500">
        <?php if (count($this->modulos) > 0) { ?>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Progresso</th>
                    <th>Data da entrega</th>
                    <th>A&ccedil;&otilde;es 
                        <a class="btn pull-right"
                            href="<?php echo $this->url(array('controller' => 'modulo', 'action' => 'relatorio')); ?>" 
                            title="Relatório Geral">
                            <img class="ui-icon ui-icon-document"/>
                        </a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->modulos as $row) { ?>
                    <tr>
                        <?php $dataEntrega = new Zend_Date($row->data_entrega); ?>
                        <td><?php echo $row->id; ?></td>
                        <td><?php echo $this->escape($row->nome); ?></td>
                        <td>
                            <?php
                                $tarefas = $row->findDependentRowset('Model_DbTable_Tarefa');
                                $percentual = 0;
                                $total = count($tarefas) * 100;
                                foreach ($tarefas as $tarefa) {
                                    $percentual = $percentual + $tarefa->percentual;
                                }$percentual = ($percentual / $total ) * 100 ;
                            ?>
                            <div class="progress progress-striped
                                 active">
                                <div class="bar"
                                     style="width: <?php echo number_format($percentual, 0); ?>%;"><?php echo number_format($percentual, 0) . "%"; ?></div>
                            </div>
                        </td>
                        <td><?php echo $this->escape($dataEntrega->get('dd/MM/yyyy')); ?></td>
                        <td>
                            <div class="btn-group" >

                                <a class="btn" 
                                   href="<?php echo $this->url(array('controller' => 'modulo', 'action' => 'edit', 'id' => $row->id)); ?>" 
                                   title="Editar">Editar</a>
                                &nbsp;

                                <?php
                                if ($tarefas != null && count($tarefas) == 0) {
                                    ?>
                                    <a class="btn" data-toggle="modal" href="<?php echo $row->id; ?>#myModal" title="Apagar">Apagar</a>
                                <? } ?>
                                    <a class="btn"
                                   href="<?php echo $this->url(array('controller' => 'modulo', 'action' => 'relatorio', 'id' => $row->id)); ?>" 
                                   title="Relatorio">Relatório</a>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>

        <?php } else { ?>
            <thead>
                <tr>
                    <th><p>Nenhum registro encontrado.</p></th>
            </tr>
            </thead>
        <?php } ?>
    </table>
</div>
<div id="paginacao">
    <?php if (!is_null($this->modulos)) { ?>
        <?php echo $this->paginationControl($this->modulos, 'Sliding', 'paginacao.phtml'); ?>
    <?php } ?>
</div>

<div class="modal" id="myModal" class="modal hide fade in" style="display: block;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Excluir Registro</h3>
    </div>
    <div class="modal-body">
        <p>Deseja excluir o registro?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" >Cancelar</a>
        <a href="<?php echo $this->url(array('controller' => 'modulo', 'action' => 'delete', 'id' => $row->id)); ?>"
           class="btn btn-primary">Confirmar</a>
    </div>
</div>