<ul class="breadcrumb">
    <li>
        <a href="<?php echo $this->baseUrl(); ?>">Home</a> <span class="divider">/</span>
    </li>
    <li class="active">Equipe</li>
</ul>
<script>
    <!--
    $(document).ready(function(){
        $('#myModal').hide();        
    });
   
    -->
</script>

<div class="btn-group">

    <form id="form_394016" class="appnitro"  method="post">
        <div class="form_description">
            <h2><span class="label label-info">Equipes</span></h2>
        </div>
        <table class="table table-striped table-bordered table-condensed" width="100%">
            <tr>
                <td>
                    <div class="field">
                        <label class="description" for="nome">Nome </label>
                        <div>
                            <input id="nome" name="nome" class="element text medium" type="text" maxlength="45" value=""/> 
                        </div>                
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="buttons">

                        <input class="btn" id="buscar" class="button_text" type="submit" name="submit" value="Buscar" />
                        <input class="btn" id="buscar" class="button_text" type="reset" name="submit" value="Limpar" />

                        <a class="btn" href="<?php echo $this->url(array('controller' => 'equipe', 'action' => 'create')); ?>" title="Incluir novo">Incluir novo</a>
                    </div>
                </td>
            </tr>
        </table>
    </form>

</div>
<br/>
<div>

    <table class="table table-striped table-bordered table-condensed" cellspacing="1" cellpadding="1" border="1" width="500">
        <?php if (count($this->equipes) > 0) { ?>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>A&ccedil;&otilde;es</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->equipes as $row) { ?>
                    <tr>

                        <td><?php echo $row->id; ?></td>
                        <td><?php echo $this->escape($row->nome); ?></td>
                        <td>
                            <div class="btn-group" >

                                <a class="btn" 
                                   href="<?php echo $this->url(array('controller' => 'equipe', 'action' => 'edit', 'id' => $row->id)); ?>" 
                                   title="Editar">Editar</a>
                                &nbsp;
                                <?php
                                $usuarios = $row->findDependentRowset('Model_DbTable_Usuario');
                                if ($usuarios != null && count($usuarios) == 0) {
                                    ?>
                                    <a class="btn" data-toggle="modal" href="<?php echo $row->id; ?>#myModal" title="Apagar">Apagar</a>
                                <? } ?>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>

        <?php } else { ?>
            <thead>
                <tr>
                    <th><p>Nenhum registro encontrado.</p></th>
            </tr>
            </thead>
        <?php } ?>
    </table>
</div>
<div id="paginacao">
    <?php if (!is_null($this->equipes)) { ?>
        <?php echo $this->paginationControl($this->equipes, 'Sliding', 'paginacao.phtml'); ?>
    <?php } ?>
</div>
<div class="modal" id="myModal" class="modal hide fade in" style="display: block;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Excluir Registro</h3>
    </div>
    <div class="modal-body">
        <p>Deseja excluir o registro?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" >Cancelar</a>
        <a href="<?php echo $this->url(array('controller' => 'equipe', 'action' => 'delete', 'id' => $row->id)); ?>"
           class="btn btn-primary">Confirmar</a>
    </div>
</div>