<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/css/fullcalendar.css' />
<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/css/fullcalendar.print.css' media='print' />
<script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/js/jquery-1.7.2.min.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/js/jquery-ui-1.8.19.custom.min.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/js/fullcalendar.min.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/js/gcal.js'></script>
<script type='text/javascript'>

    $(document).ready(function() {
	
        $('#calendar').fullCalendar({
            
                                    
            weekends: false,
            editable: false,
            theme: true,
            header: {
                left: '',
                center: 'title',
                right: 'prev,next today'
            },
            
//            events: {
//                url: 'https://www.google.com/calendar/feeds/cobra.simple.project%40gmail.com/public/basic',
//                className: 'gcal-event',           // an option!
//                currentTimezone: 'America/Belem' // an option!
//            }
            eventSources: [

                // source with no options
                "<?php echo $this->baseUrl(); ?>/auth/calendario"
//                ,
//
//                // source WITH options
//                {
//                    url: "https://www.google.com/calendar/feeds/cobra.simple.project%40gmail.com/public/basic",
//                    className: 'gcal-event',           // an option!
//                    currentTimezone: 'America/Belem' // an option!
//                }
            ],
//            events: "<?php echo $this->baseUrl(); ?>/auth/calendario",
            eventDrop: function(event, delta) {
                alert(event.title + ' was moved ' + delta + ' days\n' +
                    '(should probably update your database)');
            },
//            eventClick: function(event) {
//                // opens events in a popup window
//                window.open(event.url, 'gcalevent', 'width=700,height=600');
//                return false;
//            },
            loading: function(bool) {
                if (bool) $('#loading').show();
                else $('#loading').hide();
            }
			
        });
		
    });

</script>
<style type='text/css'>

    body {
        margin-top: 40px;
        text-align: center;
        font-size: 14px;
        font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
    }

    #loading {
        position: absolute;
        top: 5px;
        right: 5px;
    }

    #calendar {
        width: 900px;
        margin: 0 auto;
    }

</style>
<div>
    <div id='loading' style='display:none'>loading...</div>
    <div align="center">
        <ul class="nav nav-pills" style="text-align: center;">
            <li class="nav-header">
                LEGENDA: 
            </li>
            <li>
                <span class="badge badge-info">CADASTRADA</span>
            </li>
            <li>
                <span class="badge badge-warning">EM EXECUÇÃO</span>
            </li>
            <li>
                <span class="badge badge-inverse">PENDENTE</span>
            </li>
            <li>
                <span class="badge badge-success">CONCLUIDA</span>
            </li>
        </ul>
    </div>

    <div align="center">
        <a href="https://www.google.com/calendar/embed?src=cobra.simple.project%40gmail.com&ctz=America/Belem" target="_blank">Visualizar no Google Agenda</a>
    </div>
    <div id='calendar'></div>

    <div align="center">
        <a href="https://www.google.com/calendar/embed?src=cobra.simple.project%40gmail.com&ctz=America/Belem" target="_blank">Visualizar no Google Agenda</a>
    </div>
</div>    