<ul class="breadcrumb">
    <li>
        <a href="<?php echo $this->baseUrl(); ?>">Home</a> <span class="divider">/</span>
    </li>
    <li class="active">Tarefa </li>
</ul>
<script>
    <!--
    $(document).ready(function(){
        $("#dataInicio").mask("99/99/9999");
        $("#dataFim").mask("99/99/9999");
        $('#myModal').hide();
    });
    $(function() {
        $( "#dataInicio" ).datepicker();
        $( "#dataFim" ).datepicker();
    });
    -->
</script>
<div class="btn-group">
    <form id="formulario" class="appnitro"  method="post">
        <div class="form_description">
            <h2></span><span class="label label-info">Tarefas</span></h2>
        </div>
        <table class="table table-striped table-bordered table-condensed" width="100%">
            <tr>
                <td>
                    <div class="field">
                        <label class="description" for="nome">Nome </label>
                        <div>
                            <input id="nome" name="nome" class="element text large" type="text" maxlength="45" value=""/> 
                        </div>                 
                    </div>
                </td>
                <td>
                    <div class="field">
                        <label class="description" for="modulo">Modulo </label>
                        <div>
                            <select class="element select medium" id="modulo" name="modulo"> 
                                <option value="" >...</option>
                                <?php
                                foreach ($this->modulos as $row) {
                                    ?><option value="<?php echo $this->escape($row->id); ?>"><?php echo $row->nome; ?></option><?php }
                                ?>


                            </select>
                        </div> 
                    </div>
                </td>
                
                <td>
                    <div class="field">
                        <label class="description" for="situacao">Situa&ccedil;&atilde;o </label>
                        <div>
                            <select class="element select medium" id="situacao" name="situacao"> 
                                <option value="" >...</option>
                                <option value="1" >CADASTRADA</option>
                                <option value="2" >EM EXECUCAO</option>
                                <option value="3" >PENDENTE</option>
                                <option value="4" >CONCLUIDA</option>
                            </select>
                        </div> 
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="3" >
                    <div class="buttons">
                        <input class="btn" id="buscar" class="button_text" type="submit" name="submit" value="Buscar" />
                        <input class="btn" id="buscar" class="button_text" type="reset" name="submit" value="Limpar" />

                        <a class="btn" href="<?php echo $this->url(array('controller' => 'tarefa', 'action' => 'create')); ?>" title="Incluir novo">Incluir novo</a>
                    </div>
                </td>
            </tr>
        </table>
    </form>

</div>

<div>

    <table class="table table-striped table-bordered table-condensed" cellspacing="1" cellpadding="1" border="1" width="500">
        <?php if (count($this->tarefas) > 0) { ?>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Data Inicio</th>
                    <th>Data Fim</th>
                    <th>Percentual</th>
                    <th>Situa&ccedil;&atilde;o</th>
                    <th>Equipe</th>
                    <th>Modulo</th>
                    <th>A&ccedil;&otilde;es</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->tarefas as $row) { ?>
                    <tr>
                        <?php
                        $dataInicio = new Zend_Date($row->data_inicio);
                        $dataFim = new Zend_Date($row->data_fim);
                        ?>
                        <td><?php echo $row->id; ?></td>
                        <td><?php echo $this->escape($row->nome); ?></td>
                        <td><?php echo $this->escape($dataInicio->get('dd/MM/yyyy')); ?></td>
                        <td><?php echo $this->escape($dataFim->get('dd/MM/yyyy')); ?></td>
                        <td>
                            <div class="progress progress-striped
                                 active">
                                <div class="bar"
                                     style="width: <?php echo $this->escape($row->percentual); ?>%;"><?php echo $this->escape($row->percentual)."%"; ?></div>
                            </div>
                            
                        </td>
                        <?php
                        $situacao = "";
                        switch ($row->situacao) {
                            case "1": $situacao = "CADASTRADA";
                                break;
                            case "2": $situacao = "EM EXECUCAO";
                                break;
                            case "3": $situacao = "PENDENTE";
                                break;
                            case "4": $situacao = "CONCLUIDA";
                                break;
                        }
                        ?>
                        <td><?php echo $situacao; ?></td>
                        <?php $equipe = $row->findParentRow('Model_DbTable_Equipe', 'Equipe'); ?>
                        <td><?php echo $this->escape($equipe->nome); ?></td>
        <?php $modulo = $row->findParentRow('Model_DbTable_Modulo', 'Modulo'); ?>
                        <td><?php echo $this->escape($modulo->nome); ?></td>
                        <td>
                            <div class="btn-group" >

                                <a class="btn" 
                                   href="<?php echo $this->url(array('controller' => 'tarefa', 'action' => 'edit', 'id' => $row->id)); ?>" 
                                   title="Editar">Editar</a>
                                &nbsp;
                                 <?php
                                $atividade = new Model_DbTable_Atividade();
                                $atividades = $atividade->fetchAll("tarefa_id = " . $row->id,null,null,null);
                                if ($atividades != null && count($atividades) == 0) {
                                    ?>
                                    <a class="btn" data-toggle="modal" href="<?php echo $row->id; ?>#myModal" title="Apagar">Apagar</a>
                                <? } ?>
                            </div>
                        </td>
                    </tr>
    <?php } ?>
            </tbody>

<?php } else { ?>
            <thead>
                <tr>
                    <th><p>Nenhum registro encontrado.</p></th>
            </tr>
            </thead>
<?php } ?>
    </table>
</div>
<div id="paginacao">
    <?php if (!is_null($this->tarefas)) { ?>
        <?php echo $this->paginationControl($this->tarefas, 'Sliding', 'paginacao.phtml'); ?>
<?php } ?>
</div>
<div class="modal" id="myModal" class="modal hide fade in" style="display: block;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Excluir Registro</h3>
    </div>
    <div class="modal-body">
        <p>Deseja excluir o registro?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" >Cancelar</a>
        <a href="<?php echo $this->url(array('controller' => 'tarefa', 'action' => 'delete', 'id' => $row->id)); ?>"
           class="btn btn-primary">Confirmar</a>
    </div>
</div>