<?php if ($this->pageCount): ?>
    <div align="center" class="pagination">
        <ul>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
            <li>
                <a href="<?php echo $this->url(array('pagina' => $this->previous)); ?>">
                    &lt; Anterior
                </a>
            </li> 
            <?php else: ?>
                <li><a href="#">&lt; Anterior</a></li> 
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                <li>
                    <a href="<?php echo $this->url(array('pagina' => $page)); ?>">
                        <?php echo $page; ?>
                    </a>
                </li> 
                <?php else: ?>
                <li class="active"><a href="#"><?php echo $page; ?></a></li> 
                <?php endif; ?>
            <?php endforeach; ?>
            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url(array('pagina' => $this->next)); ?>">
                    Próxima&gt;
                    </a>
                </li>
            <?php else: ?>
                <li><a href="#">Próxima &gt;</a></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>