<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Cobra Project</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/view.css" media="all">
        <link type="text/css" href="<?php echo $this->baseUrl(); ?>/css/overcast/jquery-ui-1.8.19.custom.css" rel="stylesheet" />
        <link type="text/css" href="<?php echo $this->baseUrl(); ?>/css/sistema.css" rel="stylesheet" />
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/view.js"></script>
        <!--             Le javascript
                    ================================================== 
                     Placed at the end of the document so the pages load faster >-->
        <script type="text/javascript" src="http://www.google.com/jsapi"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.7.2.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui-1.8.19.custom.min.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/mascara.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery.validate.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-transition.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-alert.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-modal.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-dropdown.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-scrollspy.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-tab.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-tooltip.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-popover.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-button.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-collapse.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-carousel.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-typeahead.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery.printPage.js"></script>
        <!-- Le styles -->
        <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css" rel="stylesheet">
        <style>
            body {
                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>
        <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap-responsive.css" rel="stylesheet">
        <script>
            <!--
            $(document).ready(function(){
                $('#login_modal').hide();
                $("#form_login").validate({
                    rules: {
                        auth_email:{
                            required: true,
                            email: true 
                        },
                        auth_senha: 'required'
                    },
                    messages: {
                        auth_email: '<span class="label label-important">* Email Inválido</span>',
                        auth_senha: ' <span class="label label-important">* Senha Inválida</span>'
                    }
                });
            });
            function logMeIn() {
                scope = "https://www.google.com/calendar/feeds/";
                var token = google.accounts.user.login(scope);
            }

            function setupMyService() {
                myService = new google.gdata.calendar.CalendarService('exampleCo-exampleApp-1');
                logMeIn();
            }
            function logMeOut() {
                google.accounts.user.logout();
            }
            -->
        </script>
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="../assets/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    </head>

    <body id="main_body">

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" onclick="return false;" href="<?php echo $this->baseUrl(); ?>">Cobra Project</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
                            <?php
                            $auth = Zend_Auth::getInstance()->getIdentity();
                            if (Zend_Auth::getInstance()->getIdentity()) {
                                ?>
                                <li><a href="<?php echo $this->baseUrl(); ?>/equipe">Equipes</a></li>
                                <li><a href="<?php echo $this->baseUrl(); ?>/usuario/">Usuarios</a></li>
                                <li><a href="<?php echo $this->baseUrl(); ?>/modulo">Modulos</a></li>
                                <li><a href="<?php echo $this->baseUrl(); ?>/tarefa">Tarefas</a></li>
                            <?php } ?>
                        </ul>
                        <?php
                        if (!$auth) {//
                            ?>
                            <p class="navbar-text pull-right"> 
                                <a data-toggle="modal" href="#login_modal" title="Efetuar Login">Login</a> | 
                                <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'registro', null)); ?>">Registrar</a> </p>

                            <?php
                        } else {//
                            ?>
                            <p class="navbar-text pull-right">Seja bem vindo <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'edit', 'id' => $auth->id)); ?>">
                                    <?php echo strtolower($auth->email); ?></a> | 
                                <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout', null)); ?>">sair</a></p>
                            <?php
                        }
                        ?>
                    </div><!--/.nav-collapse -->

                </div>
            </div>
        </div>

        <div class="container">

            <?php echo $this->layout()->content; ?>

            <footer>
                <p align="center">&copy; Cobra Project <?= date("Y") == "2012" ? "2012" : "2012 - " . date("Y") ?></p>
            </footer>
        </div> <!-- /container -->
        <script>
            <!--
            $(document).ready(function(){
                $("#form_login").validate({
                    rules: {
                        auth_email: { email: true,  required: true },
                        auth_senha: 'required' 
                    },
                    messages: {
                        auth_email: '<span class="label label-important">* Campo Obrigatório</span>',
                        auth_senha: '<span class="label label-important">* Campo Obrigatório</span>'
                    }
                });
            });
            -->
        </script>
        <form id="form_login" class="navbar-search pull-right" action="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login', null)); ?>" method="post">
            <div class="modal" id="login_modal" class="modal hide fade in" style="display: block;">
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">×</a>
                    <h3>Efetuar Login</h3>
                </div>

                <div class="modal-body">
                    <p class="field"><b>E-mail: </b><input type="text" id="auth_email" name="auth_email" class="search-query medium" value="" placeholder="E-mail">
                    </p>
                    <p class="field"><b>Senha:  </b><input  type="password" id="auth_senha" name="auth_senha" class="search-query medium" value="" placeholder="Senha">
                    </p>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-info" id="login" class="button_text" type="submit" name="submit" value="Confirmar" />
                    <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'reset', null)); ?>" class="btn btn-warning"  >Esqueceu sua senha?</a>
                    <a href="#" class="btn " data-dismiss="modal" >Cancelar</a>
                </div>

            </div>
        </form>

    </body>
</html>
